import java.util.ArrayList;
import java.util.List;

/**
 * A course selection system that supports adding, removing, and listing
 * courses.
 * Course names are stored in a List and duplicate checking is case-insensitive.
 */
public class CourseSelectionSystem {

    /**
     * Processes a list of course selection commands.
     *
     * <p>
     * Supported commands are:
     * </p>
     * <ul>
     * <li>add courseName</li>
     * <li>remove courseName</li>
     * <li>list</li>
     * </ul>
     *
     * @param commands an array of command strings
     * @return the output generated by the commands, separated by new lines
     */
    public static String process(String[] commands) {
        List<String> courses = new ArrayList<>();
        StringBuilder output = new StringBuilder();

        for (String command : commands) {
            command = command.trim();

            if (command.equals("list")) {
                appendOutput(output, getCourseList(courses));

            } else if (command.startsWith("add ")) {
                String courseName = command.substring(4).trim();

                if (containsCourse(courses, courseName)) {
                    appendOutput(output, "Course already exists");
                } else {
                    courses.add(courseName);
                }

            } else if (command.startsWith("remove ")) {
                String courseName = command.substring(7).trim();

                int index = findCourseIndex(courses, courseName);

                if (index == -1) {
                    appendOutput(output, "Course not found");
                } else {
                    courses.remove(index);
                }
            }
        }

        return output.toString();
    }

    /**
     * Appends one line of output to the StringBuilder.
     * This method prevents extra blank lines and avoids a trailing newline.
     *
     * @param output the StringBuilder used to store output
     * @param text   the text to append
     */
    private static void appendOutput(StringBuilder output, String text) {
        if (output.length() > 0) {
            output.append("\n");
        }
        output.append(text);
    }

    /**
     * Returns the course list as a single string.
     * Courses are separated by comma and space.
     * If there are no courses, this method returns "No courses".
     *
     * @param courses the list of selected courses
     * @return a formatted string of selected courses
     */
    private static String getCourseList(List<String> courses) {
        if (courses.isEmpty()) {
            return "No courses";
        }
        return String.join(", ", courses);
    }

    /**
     * Checks whether a course already exists in the list.
     * The comparison is case-insensitive.
     *
     * @param courses    the list of selected courses
     * @param courseName the course name to check
     * @return true if the course exists, otherwise false
     */
    private static boolean containsCourse(List<String> courses, String courseName) {
        return findCourseIndex(courses, courseName) != -1;
    }

    /**
     * Finds the index of a course in the list.
     * The comparison is case-insensitive.
     *
     * @param courses    the list of selected courses
     * @param courseName the course name to find
     * @return the index of the course if found, otherwise -1
     */
    private static int findCourseIndex(List<String> courses, String courseName) {
        for (int i = 0; i < courses.size(); i++) {
            if (courses.get(i).equalsIgnoreCase(courseName)) {
                return i;
            }
        }
        return -1;
    }
}

/**
 * A compatibility class for judges that expect the class name CourseSelection.
 */
class CourseSelection {

    /**
     * Processes course selection commands by calling CourseSelectionSystem.process.
     *
     * @param commands an array of command strings
     * @return the output generated by the commands, separated by new lines
     */
    public static String process(String[] commands) {
        return CourseSelectionSystem.process(commands);
    }
}